-- AlterTable
ALTER TABLE "Consultation" ALTER COLUMN "startedAt" DROP NOT NULL,
ALTER COLUMN "endedAt" DROP NOT NULL,
ALTER COLUMN "charges" DROP NOT NULL,
ALTER COLUMN "status" SET DEFAULT 'REQUESTED';
